export const KEYS = {
	'LEIAUTE-PAGINATE-LIST': 'LEIAUTE-PAGINATE-LIST',
	'LEIAUTE-ACTIVE-LIST': 'LEIAUTE-ACTIVE-LIST',
	'EXTRACT-PAGINATE-LIST': 'EXTRACT-PAGINATE-LIST',
	'COLUMN-LIST': 'COLUMN-LIST',
	'LEIAUTE-REPORT': 'LEIAUTE-REPORT',
	'EXTRACT-BY-SOCIAL': 'EXTRACT-BY-SOCIAL',
	'USER-PAGINATE-LIST': 'USER-PAGINATE-LIST',
} as const;
