
@hostname=localhost
@port=3333
@host={{hostname}}:{{port}}
@prefix=development
@token={{signin.response.body.type}} {{signin.response.body.token}}


###
# @name signin
POST http://{{host}}/{{prefix}}/auth/signin HTTP/1.1
content-type: application/json

{
    "email": "admin@mail.com",
    "password": "123123"
}

###
# @name list_version
GET http://{{host}}/{{prefix}}/versions
Authorization: {{token}}

###
# @name create_version
POST  http://{{host}}/{{prefix}}/versions
Authorization: {{token}}
Content-Type: application/json

{
  "prefix": "1.1.1",
  "description": "Criando Versão"
}

###
# @name list_leiaute
GET http://{{host}}/{{prefix}}/leiaute
Authorization: {{token}}
